### ISSUE TITLE
Deployment /Failed for Microsoft.Web/serverfarms

### ISSUE THREAD

**Issue by LouFarho** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#11]
I have encountered the following error during deployment.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"This region has quota of 0 instances for your subscription. Try selecting different region or SKU."}]}

I had selected North Central US based on the products by region info and the required services. Hopefully this was a correct region.

My subscription is a Trial Subscription in an E5 developer tenant.

Please advise what steps are necessary to rectify the issue.

Thanks in advance!
Lou

**Comment by eliezerbnu** [comment]
Hello,

The error is explicit.
You don't have quota to create the resources in your subscription.
Trial is very limited in computational resources.
Go to the "Usage + Quotas" tab in your subscription to check.
By default, neo json deploys a Standard 2 web app with 2 vcpu and 3.5 GB of ram.
![azure](https://user-images.githubusercontent.com/53222753/109934981-ddf4ec80-7cab-11eb-88cd-fb7dc839123a.jpg)
