### ISSUE TITLE
Bot asks for credentials.

### ISSUE THREAD

**Issue by pfinkler** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#12]
I was able to successfully get the app template deployed in Azure and deploy the teams app.  Unfortunately, nothing seems to be working any I’m not sure how to identify what the issue is.  The onboarding bot just responds with “Something went wrong. Try again in a few minutes.”  It also is asking for users to sign in.  Any ideas what might cause this behavior and how I can go about troubleshooting it?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
