### ISSUE TITLE
Cannot figure out complete learning plan url and new hire question from SharePoint

### ISSUE THREAD

**Issue by vpintugorai** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#13]
The steps "Step 3: Configure SharePoint Hub" in the deployment guide are not clear.
Need more details in steps.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
