### ISSUE TITLE
Build Failed | Beta Graph API to fetch user profile note is failing

### ISSUE THREAD

**Issue by vpintugorai** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#14]
Build Failed, following error is found in log under App Service > Deployment Center > logs- 

"Build Failed: 

Following error in log:
> newhireonboarding@1.0.0 build D:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\ClientApp
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node D:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\ClientApp\node_modules\react-scripts\scripts\build.js[8632]: c:\ws\src\env-inl.h:957: Assertion `(ret) != (nullptr)' failed.
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! newhireonboarding@1.0.0 build: `react-scripts build`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the newhireonboarding@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! D:\local\AppData\npm-cache\_logs\2021-04-23T13_12_13_639Z-debug.log
D:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj(168,3): error MSB3073: The command "npm run build" exited with code 134.
Done Building Project "D:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj" (default targets) -- FAILED.

Build FAILED."

Also tried following - 
i) Failed after redeploy.
ii) I have deleted node_modules manually and redeploy, still failed

Find the full log - 
[redeply_app_service_2.txt](https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/files/6382246/redeply_app_service_2.txt)

![image](https://user-images.githubusercontent.com/82500579/116193890-b1120280-a74d-11eb-8921-2ade9d63ce10.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
