### ISSUE TITLE
adding to Teams Channel as a Tab - failure

### ISSUE THREAD

**Issue by singupuramp** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#15]
When I try to add the app as tab to the existing Teams channel, getting below exceptions, any insight would be grateful.

"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

[error.pdf](https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/files/6394191/error.pdf)
![image](https://user-images.githubusercontent.com/49993583/116459441-aa04f600-a81a-11eb-97d8-8e50eb4fa076.png)

**Comment by aidab98** [comment]
Did you manage to know the issue/solution for this?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
