### ISSUE TITLE
<BotError>Bot returned unsuccessful status code NotImplemented

### ISSUE THREAD

**Issue by koskimiesl** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#16]
Hello, any ideas why the bot returns `<BotError>Bot returned unsuccessful status code NotImplemented` after clicking "Introduce yourself" in Teams? HTTP 502 is the response code to the "invoke" request. It shows "Unable to reach app. Please try again" for the user. Please see screenshot below:

![image](https://user-images.githubusercontent.com/2557669/119679341-f3ac2500-be48-11eb-97dc-39dd77850c1c.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
