### ISSUE TITLE
Cannot find Option in Deployment Guide on Azure Portal

### ISSUE THREAD

**Issue by Dougydoe** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#18]
Hello,

I am working through the deployment guide to deploy the New Employee Onboarding App for my organisation but I have hit a block.

On Step 6, number 3, I don't seem to see the **Add Setting** option under the **Settings** options as stated. Grateful if you can point me in the right direction. 

I have attached screenshots if that helps

<img width="685" alt="Azure Bot_DocScreen" src="https://user-images.githubusercontent.com/47186116/121080808-d4f84780-c7d3-11eb-9e52-79198279e7a2.PNG">

<img width="379" alt="Azure Bot_PortalScreen" src="https://user-images.githubusercontent.com/47186116/121080837-db86bf00-c7d3-11eb-9655-2d9df9a220a0.PNG">

**Comment by dmitrydyachenko** [comment]
In the "Settings" tab -> "Configuration" -> click "Add OAuth Connection Settings" and then you will see the form to fill in.

**Comment by Dougydoe** [comment]
Hi Dmitry,

Thanks for getting back to me on this. Yes, I managed to figure it out
earlier however, I did run into another issue which I think you might be
able to help me with.

After filling in the form via the Add OAuth Connection Settings, when I
tested it, I got the message saying the Client Secret was invalid (Figure 1
and 2 below).  However, I was using the Client secret I created from the
App Registration of the Bot (Figure 3 below)

Any idea what might be going wrong and how to fix this?

1.
[image: image.png]
2.
[image: image.png]
3.
[image: image.png]

Regards,
Douglas

**Comment by dmitrydyachenko** [comment]
Hi Douglas, I can't see your screenshots:

![image](https://user-images.githubusercontent.com/18660673/123084854-85dc2480-d419-11eb-9380-a6b3f75064c0.png)

**Comment by Dougydoe** [comment]
Sorry about that. Must be Gmail's fault as they were showing when I sent
the email.

I've attached them here in PNG format.

Thanks

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
