### ISSUE TITLE
New Employee Onboarding App is not Microsoft published

### ISSUE THREAD

**Issue by amitrg-orion** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#19]
Hi,

We are getting the following confirmation message when trying to install the NEO template. The message here says that the app is not published by Microsoft that concerns Me and our client. Can you please look into it as soon as possible.
![image](https://user-images.githubusercontent.com/85952792/122084730-17bbb000-cdd0-11eb-91dc-aa1d3dbe756e.png)

Thanks
Amit

**Comment by v-kalc** [comment]
Hi Amit
Accepting the consent permissions will let you give all rights for access of the site, Please accept it to move forward. 
And one more can you please double check on the Application permissions which you have done in one of the deployment step whether you have granted permissions or not.

**Comment by J04nn4** [comment]
The app is not Microsoft licensed. Treat it as a template you use and customize but not as a built out application. Legal info here https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding#legal-notice

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
