### ISSUE TITLE
InvalidBotData while deploying time

### ISSUE THREAD

**Issue by rajeshravipati** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#20]
![image](https://user-images.githubusercontent.com/85662930/123742527-6b96c080-d8c9-11eb-8d05-9e321763402e.png)

plz help me on this

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
