### ISSUE TITLE
SharePoint configuration page, invalid lookbook

### ISSUE THREAD

**Issue by quidan** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#21]
It appears that the lookbook link on the following page is no longer valid:
https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/wiki/SharePoint-configuration

Clicking https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19 redirects you to https://lookbook.microsoft.com/. 

It appears that https://lookbook.microsoft.com/details/388a159f-475b-4557-9088-c9073a26c576 may be the new version.

**Comment by timthrash** [comment]
Do we know if this is the right Lookbook link?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
