### ISSUE TITLE
unable to  add the feed back tab  in teams   

### ISSUE THREAD

**Issue by rajeshravipati** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#23]
unable to  add the feed back tan in teams (Deploy using publishing and vs code deployment using build and publish commands )
![Screenshot_1](https://user-images.githubusercontent.com/85662930/124566556-c9df1880-de60-11eb-85cb-01b365b9830e.png)
![Dep](https://user-images.githubusercontent.com/85662930/124566578-cea3cc80-de60-11eb-963c-c10c0c185ff8.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
