### ISSUE TITLE
"Something went wrong. Try again in a few minutes" error

### ISSUE THREAD

**Issue by ghost** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#25]
I have followed the deployment guide four times, without a successful deployment of this solution. Each time I deploy, go into the "test in web chat" or sideload into Teams and (in both locations) get a "Something went wrong. Try again in a few minutes" error message from the bot. Any thoughts on why this is occurring?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
