### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by MichaelRoth42** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#26]
I followed the whole deployment process and had no issues. When I want to install the app in Teams however, I get the error message "Something went wrong"

Which is not helpful at all

![image](https://user-images.githubusercontent.com/58400001/129051509-c9278cf3-9088-4204-beb5-db5f51ca58c3.png)

The package manifest run through without any errors, so I guess the issues can't be in the manifest, right?

I have no idea where to look

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
