### ISSUE TITLE
App Template Deploy always fails in Build Stage

### ISSUE THREAD

**Issue by nirmas** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#27]
I've been trying to deploy the New Employee Onboarding Teams app template available here https://aka.ms/teamsapptemplates, but this always fails. 

![image](https://user-images.githubusercontent.com/73279595/129141586-88f63a8e-22a2-4967-a805-6d5d4be36e56.png)

![image](https://user-images.githubusercontent.com/73279595/129141627-843b7d7d-5145-4da7-bea4-3a69152f37d9.png)
{

    "status": "Failed",

    "error": {

        "code": "ResourceDeploymentFailure",

        "message": "The resource operation completed with terminal provisioning state 'Failed'."

    }

}

Tried to redeploy the source controls several times on the app service - fails on build all the time -

C:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\ClientApp\node_modules\react-scripts\scripts\build.js[6100]: c:\ws\src\env-inl.h:957: Assertion `(ret) != (nullptr)' failed.
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! newhireonboarding@1.0.0 build: `react-scripts build`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the newhireonboarding@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\local\AppData\npm-cache\_logs\2021-08-10T10_41_25_551Z-debug.log
C:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj(168,3): error MSB3073: The command "npm run build" exited with code 134.
Done Building Project "C:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj" (default targets) -- FAILED.

Build FAILED.

"C:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj" (default target) (1:7) ->
(PublishRunWebpack target) ->
C:\home\site\repository\Source\Microsoft.Teams.Apps.NewHireOnboarding\Microsoft.Teams.Apps.NewHireOnboarding.csproj(168,3): error MSB3073: The command "npm run build" exited with code 134.

0 Warning(s)
1 Error(s)

**Comment by nirmas** [comment]
More Error Details 

![image](https://user-images.githubusercontent.com/73279595/129142291-78f5810e-3921-4823-be6c-993f3196222e.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
