### ISSUE TITLE
The template does not specify the name of the azure key vault should be shorter 

### ISSUE THREAD

**Issue by geo-msft** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#28]
I was trying to deploy this template and the deployment failed with this error: 
{

    "status": "Failed",
    "error": {
        "code": "VaultNameNotValid",
        "message": "The vault name 'BrusselsNewEmployeeOnBoardingvault' is invalid. A vault's name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147742"

    }
}

I find it more intuitive to specify this constraint in the deployment guide itself, rather than making the developer search for the error, then find the official docs: 
https://docs.microsoft.com/en-us/azure/key-vault/general/quick-create-cli#create-a-key-vault: 

"Key vault name: A string of 3 to 24 characters that can contain only numbers (0-9), letters (a-z, A-Z), and hyphens (-)"  

That would save time for the developers trying to deploy the template. Thank you!

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
