### ISSUE TITLE
The deployment guide does not which are the resources getting created in the resource group after the deployment

### ISSUE THREAD

**Issue by geo-msft** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#29]
The deployment guide does not specify the complete set of resources which get created after deploying this ARM template. The developer deploying this template needs to inspect the ARM JSON in order to understand what's getting created. I find it nice to have in the guide: 
- an explanation with all the resources which get deployed, 
- the naming requirements for each resource
- and the purpose of each resource. 

Thank you.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
