### ISSUE TITLE
Troubleshooting Tips + Documentation Clarification

### ISSUE THREAD

**Issue by nhtngo** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#30]
Below are updates to the documentations and clarifications on few steps during deployment:

### **1. Configuring SharePoint**
The new lookbook URL is https://lookbook.microsoft.com/details/388a159f-475b-4557-9088-c9073a26c576. After deploying the site, continue with adding in a question to the NewHireQuestionnaire and verify that the New Hire Checklist has the required columns as described in the [SharePoint Configuration guide](https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/wiki/SharePoint-configuration)

### **2. Setting up users and managers in test tenant**
If you are using a test tenant, please make sure that all test users have the correct managers assigned. New Employee Onboarding uses the User Details in AAD to determine whether someone is a New Hire or a Manager. You can set up your tenant users through _Azure Portal > Azure Active Directory > Users_

### **3. Deploying ARM Template**
When deploying the template, we recommend the following:
- **Base Resource Name** should be less than 19 as the KeyVault should be less than 24 characters and the ARM template naming for KeyVault is "{base resource name}vault"
- Suggest that **Base Resource Name** be given in all lower cases to prevent case sensitivity in future applications
- **Human Resource Link** must be a **team** and not a channel. To get Team link, refer to the below screenshot:![image](https://user-images.githubusercontent.com/91352558/135664777-6865bc8d-321a-46ab-91c5-af865dd39e17.png)
- **SharePoint tenant name** should be in the form of _*****.sharepoint.com_

### **4. Verify Deployment Status**
Before uploading the manifest to Teams, check the deployment status (steps below):
  1. Go to Azure Portal and navigate to the Resource Group
  2. Click on the Deployments:
      ![image](https://user-images.githubusercontent.com/91352558/135665779-3ff5eecb-bd95-4a6b-8fe7-2cce81f5b486.png)
  3. If the deployment completed with the terminal provisioning state "Failed", then you will need to re-sync deployment. The transitive dependency set of the front-end web app pulls in over 1,000 NPM packages, and sometimes there is an error fetching all of the packages. To fix, please do the following:
  4. Go to the "Deployment center" section of the app service that failed to deploy.
  5. Click on "Sync" to restart the deployment.
![image](https://user-images.githubusercontent.com/91352558/135667420-f70ccdf3-5ec2-4ea6-9778-3cadf231e313.png)

### **5. Failing to Sync Multiple Times**
If you are continuously unsuccessful with syncing your deployment from Section 4, you will need to delete the node_modules folder and try syncing again:
  1. On Azure Portal, open the app service
  2. Click on the url provided (https://******.azurewebsites.net)
  3. Add **.scm** to the URL (https://******.scm.azurewebsites.net)
  4. Click on "Debug Console" on the top menu then "CMD"
  5. Navigate to Site > repository > Source > Microsoft.Teams.Apps.NewHireOnboarding > ClientApp
  6. Delete "node_modules" folder or rename it to "node_modules_old"
  7. Retry syncing the deployment again as described in Section 4

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
