### ISSUE TITLE
Error with the introduce yourself feature

### ISSUE THREAD

**Issue by sptechmk** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#31]
Post troubleshooting I was able to deploy the solution but the App doesn't work completely. Facing the issue with 'Introduce yourself'. I see the app insights record several instances of 
:_IDX10501: Signature validation failed. Unable to match key: kid: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Exceptions caught: '[PII is hidden.

**Comment by aidab98** [comment]
Facing this issue as well

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by sptechmk** [comment]
@v-saikirang , Sorry but I continue to face the issue and it isn't resolved.
