### ISSUE TITLE
SSO doesn't work with SharePoint List in Teams tab

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#32]
After the solution is deployed and when the user tries to access the New Employee Checklist from the Teams tab app, nothing happens.
It is expected that the user is authenticated and access the SharePoint List content directly within the MS Teams tab app

On Teams web client, the user needs to be authenticated on SPO first - In that case, he can access the content from the Teams tab - This is due to the authent cookie from the SPO connection being reused in the context of Teams.

On the desktop / mobile client, the authentication flow is not trigger and nothing happens.

Based on the description of this app, the user should be able to access SharePoint from MS Teams tab

**Comment by Porkai-Pandian** [comment]
Hi @timoleo23,

Thank you for raising the issue, we're looking into it and get back to you as early as possible.

**Comment by timoleo23** [comment]
Hi @Porkai-Pandian, did you have the chance to check? NEO app deployment is on hold until we get clarification on this observed behavior.

**Comment by Porkai-Pandian** [comment]
Hi @timoleo23, we're able to reproduce the issue for desktop client, reached out to team to confirm if it's known issue or any work around, will let you know once I've more updates

**Comment by dthanawa** [comment]
Hi @Porkai-Pandian,
I am facing the same issue with one of my client's deployments. Is your team able to fix the problem?

**Comment by amitrg-orion** [comment]
Hi @Porkai-Pandian 
We are facing the same issue for one of our Clients. Can we understand the timeline for when this will be fixed?
Thanks
Amit Gaonkar

**Comment by Porkai-Pandian** [comment]
This is no longer is a bug, and it's works fine, if you still face the issue, please create a new issue so that we can assist you accordingly.
