### ISSUE TITLE
"something went wron. Try again in a few minutes"

### ISSUE THREAD

**Issue by aidab98** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#37]
![image](https://user-images.githubusercontent.com/86289425/152933483-34402cac-7377-4e51-ac02-5b8883cfc96b.png)
When I submit a new introduction or type employee checklist the bot responds with something went wrong try again in a few minutes.

**Comment by Porkai-Pandian** [comment]
Hi @aidab98,

Thank you for raising the issue, as per your email, issue got resolved, please confirm so that we can close this issue.

**Comment by TLS1-2** [comment]
How was this issue resolved? I am encountering 'something went wrong' error too.

**Comment by TLS1-2** [comment]
@Porkai-Pandian How was this issue resolved?
