### ISSUE TITLE
Something went wrong. Try again in a few minutes.

### ISSUE THREAD

**Issue by TLS1-2** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#38]
Encountering two errors in Teams app:

1) Something went wrong. Try again in a few minutes.
2) Clicking 'Take a tour' or 'Review introductions' button errors out with "Unable to reach app. Please try again."

![image](https://user-images.githubusercontent.com/99691048/153947378-7ece984d-5344-4bfd-bd87-521abcbad1aa.png)

**Comment by Porkai-Pandian** [comment]
Hi @TLS1-2,

Thank you for posting your query, can you please check your application insights and see the exceptions that logged and share it for us to troubleshoot further? It seems the bot is not able to communicate with the app service.

**Comment by TLS1-2** [comment]
@Porkai-Pandian Here are the top 3 exception from Application Insights

**EXCEPTION-1** Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException
Message: IDX10501: Signature validation failed. Unable to match key: kid: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Exceptions caught: '[PII is hidden
Exception Type: Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException |  
Failed Method: System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature
Formatted Message: Failed to validate the token.

**EXCEPTION-2** Microsoft.Graph.ServiceException 
Message: Code: Request_ResourceNotFound Message: Resource 'manager' does not exist or one of its queried reference-property objects are not present.
Exception Type: Microsoft.Graph.ServiceException
Formatted Message: Failed to get manager for user: 0e84df5b-cd15-4ade-84f8-b11b7795c8cd. Status Code: NotFound Exception: Code: Request_ResourceNotFound
Message: Resource 'manager' does not exist or one of its queried reference-property objects are not present.

**EXCEPTION-3** Microsoft.Rest.HttpOperationException
Message: Operation returned an invalid status code 'BadRequest'
Exception type: Microsoft.Rest.HttpOperationException
Formatted Message: Exception caught : Operation returned an invalid status code 'BadRequest'

**Comment by Porkai-Pandian** [comment]
Thank you @TLS1-2 for sharing the errors, I'll check the reason for the first exception and get back to you, however the second exception status that the resource doesn't exist, did the deployment succeed for you.

**Comment by Porkai-Pandian** [comment]
Hi @TLS1-2,

Please share your availability and email id so that we can connect and troubleshoot over the call.

**Comment by Porkai-Pandian** [comment]
Hi @TLS1-2, do you've any updates on the above ask.

**Comment by Porkai-Pandian** [comment]
Closing the issue due to inactivity, please create new issue if it still happens.
