### ISSUE TITLE
Feedback function not working

### ISSUE THREAD

**Issue by sptechmk** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#39]
Hello Team while I was able to deploy the solution, I continue to see the Feedback functionality(it goes on loop for sign-in) not working in the NEO app. Is this a bug?

**Comment by Porkai-Pandian** [comment]
Hi @sptechmk 

Thank you for submitting the issue, we're looking into and get back to you soon with updates.

**Comment by Porkai-Pandian** [comment]
Hi @sptechmk, Feedback functionality is working fine, it's not a bug, we can discuss to troubleshoot further.

**Comment by Porkai-Pandian** [comment]
HI @sptechmk,

Please let us know if you've any updates, if not we'll proceed with closing the issue.
