### ISSUE TITLE
Signin Error

### ISSUE THREAD

**Issue by aidab98** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#44]
Hello,
User is facing the below issue while accessing the app.
![NEO error](https://user-images.githubusercontent.com/86289425/168999458-55c0d6f8-df93-4a5c-90c4-9e049537c79c.png)

How should this be resolved and what is causing this issue?

**Comment by Porkai-Pandian** [comment]
Hi @aidab98,

Whenever the session expires users will see this message “The Sign In code was not found or expired. Please try asking the bot to sign in again.”

Just type “Logout” and then “Login”, provide the necessary credentials, bot should work fine with this issue.
