### ISSUE TITLE
Error once app installed

### ISSUE THREAD

**Issue by seize9eme** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#5]
Have encountered several issues while installing the app template.
First trying to install it in a Teams Channel server IP address could not be found.
While trying to talk with the bot, error message and an authentication button but clicking on it doesn't do anything.
![Screenshot 2020-11-16 204839](https://user-images.githubusercontent.com/64589783/99300781-51820380-284d-11eb-868b-c4f1807ae6d9.png)
![Screenshot 2020-11-16 204846](https://user-images.githubusercontent.com/64589783/99300793-53e45d80-284d-11eb-9142-4b16da4adc93.png)

**Comment by Mikhail2k15** [comment]
I had the same issues. Sign in the issue you can resolve by adding "token.botframework.com" into the valid domain section. For more detail ping me via Teams/email. My alias is mibon.

**Comment by seize9eme** [comment]
@Mikhail2k15  awesome!!! it works! have provided the feedback to update the documentation.

**Comment by seize9eme** [comment]
@Mikhail2k15 I still have the first issue when trying to install in a Teams Channel.... 
![Screenshot 2020-11-16 204839](https://user-images.githubusercontent.com/64589783/100752980-81064380-33e9-11eb-90a8-b01294acfd56.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
