### ISSUE TITLE
Error deploying the solution in Azure (App Service)

### ISSUE THREAD

**Issue by omg1978** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#6]
After performing the previous steps indicated in the installation guide, when deploying the NEO solution in Azure, I receive this error:

![ErrorProv](https://user-images.githubusercontent.com/275557/102266033-34a62200-3f18-11eb-8a29-0f532d0a94eb.jpg)

`{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}`

I think it can be a problem when trying to download many packages or frameworks that use the web solution, this takes a lot of time and gives an error.

**Comment by maiomardesouki** [comment]
I'm getting the same error, did you manage to solve it??

**Comment by omg1978** [comment]
Hi mate, at the moment I don't have a "clean" solution. As a workaround, you can download the web solution to local, copy it with Visual Studio and then download it from local to the app service in Azure.

**Comment by omg1978** [comment]
> I'm getting the same error, did you manage to solve it??

Hi mate, at the moment I don't have a "clean" solution. As a workaround, you can download the web solution to local, copy it with Visual Studio and then download it from local to the app service in Azure.

**Comment by ginaglahn** [comment]
I had the same issue, just did a redeploy and it worked.  Actually very quickly the second time.

**Comment by omg1978** [comment]
> I had the same issue, just did a redeploy and it worked. Actually very quickly the second time.

In which region do you have the App Service installed? I have all the services in Western Europe and it is complicated to deploy the web solution, due to the time-out. I have tried to redeploy it, with the same time-out result.

**Comment by ginaglahn** [comment]
I installed it in the US West

**Comment by eliezerbnu** [comment]
I'm getting the same error.
The error occurs during deploy via npm.
I monitored the Deployment center tab of Azure Web App:
![onboarding-error](https://user-images.githubusercontent.com/53222753/109849706-7057aa80-7c30-11eb-8a4d-8573ab9d06fb.jpg)

I collected the logs:
[Running deployment command.txt](https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/files/6078111/Running.deployment.command.txt)

Does anyone have any idea how to solve this problem?
I installed it in the East US.

**Comment by eliezerbnu** [comment]
Hello, 
I did the deployment of the application successfully.
After several searches on the npm error 134, I found this post saying that the problem is out of memory. 
[https://stackoverflow.com/questions/59766839/error-code-elifecycle-npm-err-errno-134](url)

By default, a Plan S2 service is deployed.
I changed it to S3, with twice the memory and cpu:
![neo-sp](https://user-images.githubusercontent.com/53222753/109871778-4dd28b00-7c4a-11eb-8530-66eb3e4e8d13.jpg)


I went back to the deployment center tab of the azure web app, clicked Redeploy/Sync and waited until I completed the process successfully.
![neo-success](https://user-images.githubusercontent.com/53222753/109871740-3e534200-7c4a-11eb-891a-3e124b6df504.jpg)

Good Luck for all.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
