### ISSUE TITLE
Sign-in prompt doesn't follow the bot design guideline

### ISSUE THREAD

**Issue by cagrimunyas** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#7]
There is a serious design issue:
- When user first installs the app, the bot sends a prompt to user to sign-in
- ->If user clicks on the "Sign-in" button and fails to authenticate on the first try:
- ----> The same button no longer works saying "The Sign In code was not found or expired. Please try asking the bot to sign in again."
- ---->The bot never send another prompt to sign-in if the previous attempt fails
- ----> If the user tries to use a functionality that requires users' identity (which is most of the app), the auth. fails and it never send another sign-in request.  : `Signature validation failed. Unable to match key`
- `Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=XXXXXXXXXX) at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=XXXXXXXXXX) at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=3.1.7.0, Culture=neutral, PublicKeyToken=XXXXXXXXXX)`

**Comment by aidab98** [comment]
Also facing this problem now.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by rodriguesnich** [comment]
> Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

Hello! 
I'm having a similar error, when the user tries to login a while after the message was sent, is there any work around I can do for a better user experience?
